#!/usr/bin/env python
# coding: utf-8

# # Tarea - Programación lineal

# ### Diseño de la Dieta Óptima
# 
# Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en $100$ gramos, se deben tener **por lo menos** $8$ gramos de proteína y $6$ gramos de grasa. Así mismo, no se debe tener más de $2$ gramos de fibra y $0.4$ gramos de sal.  
# 
# Los datos nutricionales se pueden obtener de la siguiente tabla:
# 
# Ingrediente|Proteína|Grasa|Fibra|Sal
# :----|----|----|----|----
# Pollo|  10.0%|08.0%|00.1%|00.2%
# Carne|  20.0%|10.0%|00.5%|00.5%
# Cordero|15.0%|11.0%|00.5%|00.7%
# Arroz|  00.0%|01.0%|10.0%|00.2%
# Trigo|  04.0%|01.0%|15.0%|00.8%
# Gel|    00.0%|00.0%|00.0%|00.0%
# 
# Los costos de cada producto son:
# 
# Ingrediente|Costo por gramo
# :----|----
# Pollo|$\$$0.013
# Carne|$\$$0.008
# Cordero|$\$$0.010
# Arroz|$\$$0.002
# Trigo|$\$$0.005
# Gel|$\$$0.001    
# 
# Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total. Para simplificar la notación use las siguientes variables: 
# 
# + $x_1:$ Gramos de pollo  
# + $x_2:$ Gramos de carne  
# + $x_3:$ Gramos de cordero  
# + $x_4:$ Gramos de arroz  
# + $x_5:$ Gramos de trigo  
# + $x_6:$ Gramos de gel
# 
# La tarea consiste en plantear el problemade programación lineal que permita satisfacer las necesidades alimenticias del gato al tiempo que minimice el costo total y resolverlo con `linprog`.

# In[ ]:





# ### Problema de distribución de energía eléctrica
# 
# La Comisión Federal de Electricidad **(CFE)** dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas $1$, $2$ y $3$ pueden satisfacer $80$, $40$ y $60$ millones de KW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de $70$, $40$ y $70$ millones de Kw al día respectivamente. 
# 
# 
# Los costos asociados al envío de suministro energético por cada millón de Kw entre cada planta y cada ciudad son los registrados en la siguiente tabla. 
# 
# -|Guadalajara|León|Morelia
# :----|----|----|----
# Planta 1|5|2|7
# Planta 2|3|6|6
# Planta 3|6|1|2
# 
# Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada planta (en millones de KW) y cada ciudad.
# 
# Para simplificar la notación use las siguientes variables:
# 
# + $x_1$: Kw (en millones) distribuidos de la Planta 1 a Guadalajara
# + $x_2$: Kw (en millones) distribuidos de la Planta 1 a León
# + $x_3$: Kw (en millones) distribuidos de la Planta 1 a Morelia
# + $x_4$: Kw (en millones) distribuidos de la Planta 2 a Guadalajara
# + $x_5$: Kw (en millones) distribuidos de la Planta 2 a León
# + $x_6$: Kw (en millones) distribuidos de la Planta 2 a Morelia
# + $x_7$: Kw (en millones) distribuidos de la Planta 3 a Guadalajara
# + $x_8$: Kw (en millones) distribuidos de la Planta 3 a León
# + $x_9$: Kw (en millones) distribuidos de la Planta 3 a Morelia
# 
# La tarea consiste en plantear el problema de programación lineal que permita satisfacer las necesidades de todas las ciudades al tiempo que minimice los costos asociados a la distribución y resolverlo con `linprog`.

# 
# ### __Restricciones de la oferta:
# x1+x2+x3<=80
# x4+x5+x6<=40
# x7+x8+x9<=60
# 
# ###  __Restricciones de la demanda:
# x1+x4+x7=>70
# x2+x5+x8=> 40
# x3+x6+x9=>70
# ### _Función objetivo:_
# 
# __min x1,....,x9 :  5x1+2x2+7x3+3x4+6x5+6x6+6x7+1x8+2x9
# 

# In[17]:


import numpy as np
import scipy.optimize as opt



a= np.array ([5,
             2,
             7,
             3,
             6,
             6,
             6,
             1,
             2,])
B= np.array([[1,1,1,0,0,0,0,0,0],
            [0,0,0,1,1,1,0,0,0],
            [0,0,0,0,0,0,1,1,1],
            [-1,0,0,-1,0,0,-1,0,0],
            [0,-1,0,0,-1,0,0,-1,0],
            [0,0,-1,0,0,-1,0,0,-1]
            ])
c= np.array ([80,
             40,
             60,
             -70,
             -40,
             -70])
respuesta=opt.linprog(a,B,c, method="simplex")


# In[18]:


respuesta.x

[out]: array([30., 40., 10., 40.,  0.,  0.,  0.,  0., 60.])


# In[ ]:





